name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore bonkdec/bonkdec.sln
    - name: Build
      run: dotnet build bonkdec/bonkdec.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test bonkdec/bonkdec.sln --no-restore --verbosity normal
  Debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore bonkdec/bonkdec.sln
    - name: Build
      run: dotnet build bonkdec/bonkdec.sln --configuration Debug --no-restore
    - name: Test
      run: dotnet test bonkdec/bonkdec.sln --no-restore --verbosity normal
